/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelaCadastro;

import ClasseCadastro.Cargo;
import ClasseCadastro.Usuario;
import Pesquisa.Pesquisa;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static trabalhoprogramacao2.TelaPrincipal.listaUsuarios;
import static trabalhoprogramacao2.TelaPrincipal.usuarioSelec;

/**
 *
 * @author Vanila
 */
public class TelaUsuarios extends javax.swing.JDialog {

    Path verificaSeExiste = Paths.get("C:\\Users\\Public\\Documents\\usuarios.data");
    boolean editar = false;

    /**
     * Creates new form TelaUsuarios
     */
    public TelaUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        BtCancelar.setVisible(false);
        Btgravar.setVisible(false);
        this.configuraBotao(2);
        this.iniciaSistema();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboboxCargo = new javax.swing.JComboBox<>(ClasseCadastro.Cargo.values());
        LabelCargo = new javax.swing.JLabel();
        Btgravar = new javax.swing.JButton();
        BtEditar = new javax.swing.JButton();
        labelLogin = new javax.swing.JLabel();
        BtPesquisar = new javax.swing.JButton();
        TxtLogin = new javax.swing.JTextField();
        BtCancelar = new javax.swing.JButton();
        labelSenha = new javax.swing.JLabel();
        BtExcluir = new javax.swing.JButton();
        TxtSenha = new javax.swing.JPasswordField();
        BtNovo = new javax.swing.JButton();
        TxtConfirmaSenha = new javax.swing.JPasswordField();
        LabelConfirmaSenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuário");

        ComboboxCargo.setEditable(true);

        LabelCargo.setText("Cargo:");

        Btgravar.setText("Gravar");
        Btgravar.setFocusable(false);
        Btgravar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btgravar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Btgravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtgravarActionPerformed(evt);
            }
        });

        BtEditar.setText("Editar");
        BtEditar.setAlignmentY(0.0F);
        BtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditarActionPerformed(evt);
            }
        });

        labelLogin.setText("Login:");

        BtPesquisar.setText("Pesquisar");
        BtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesquisarActionPerformed(evt);
            }
        });

        BtCancelar.setText("Cancelar");
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });

        labelSenha.setText("Senha:");

        BtExcluir.setText("Excluir");
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        BtNovo.setText("Novo");
        BtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoActionPerformed(evt);
            }
        });

        LabelConfirmaSenha.setText("Confirme a senha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btgravar)
                                .addGap(18, 18, 18)
                                .addComponent(BtExcluir))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(BtEditar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtPesquisar))
                    .addComponent(TxtLogin)
                    .addComponent(TxtSenha)
                    .addComponent(TxtConfirmaSenha)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSenha)
                            .addComponent(LabelConfirmaSenha)
                            .addComponent(ComboboxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelCargo)
                            .addComponent(labelLogin)
                            .addComponent(BtCancelar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelConfirmaSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(LabelCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboboxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btgravar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtEditar)
                        .addComponent(BtExcluir)
                        .addComponent(BtPesquisar)
                        .addComponent(BtNovo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtCancelar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoActionPerformed
        this.configuraBotao(1);
    }//GEN-LAST:event_BtNovoActionPerformed

    private void BtgravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtgravarActionPerformed

        if (this.TxtSenha.getText().equals(this.TxtConfirmaSenha.getText())) {

            if (this.TxtLogin.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Por favor para prosegui insira um login válido");

            } else if (this.TxtSenha.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Por favor para prosegui insira uma senha válida");

            } else {

                if (editar == true) {
                    for (int i = 0; i < listaUsuarios.size(); i++) {

                        if (usuarioSelec.getLogin().equals(listaUsuarios.get(i).getLogin())
                                && usuarioSelec.getSenha().equals(listaUsuarios.get(i).getSenha())) {

                            listaUsuarios.get(i).setLogin(TxtLogin.getText());
                            listaUsuarios.get(i).setSenha(TxtSenha.getText());
                            listaUsuarios.get(i).setCargo((Cargo) ComboboxCargo.getSelectedItem());
                            this.editar = false;
                            break;

                        }

                    }
                } else {
                    Usuario usu = new Usuario(this.TxtLogin.getText(), this.TxtSenha.getText(), (Cargo) this.ComboboxCargo.getSelectedItem());
                    listaUsuarios.add(usu);
                }

                if (this.salvarUsuario() == true) {
                    TxtLogin.setText(null);
                    TxtSenha.setText(null);
                    TxtConfirmaSenha.setText(null);
                    JOptionPane.showMessageDialog(null, "Salvo com sucesso!");

                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Senhas diferentes por favor verifique!.");
        }


    }//GEN-LAST:event_BtgravarActionPerformed

    private void BtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditarActionPerformed
        this.configuraBotao(1);
        this.editar = true;
    }//GEN-LAST:event_BtEditarActionPerformed

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar?", "Atenção", JOptionPane.YES_NO_OPTION) == 0) {
            TxtLogin.setText(null);
            TxtSenha.setText(null);
            TxtConfirmaSenha.setText(null);
            configuraBotao(2);
        }
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        for (int i = 0; i < listaUsuarios.size(); i++) {
            if (listaUsuarios.get(i).getLogin().equals(TxtLogin.getText())
                    && listaUsuarios.get(i).getSenha().equals(TxtSenha.getText())) {
                listaUsuarios.remove(i);
                if (this.salvarUsuario()) {
                    TxtLogin.setText(null);
                    TxtSenha.setText(null);
                    TxtConfirmaSenha.setText(null);
                    JOptionPane.showMessageDialog(null, "Usuário removido!");
                }
            }
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void BtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesquisarActionPerformed
        Pesquisa pesquisar = new Pesquisa(null, true, 1);

        pesquisar.setLocationRelativeTo(null);
        pesquisar.setModal(true);
        pesquisar.setVisible(true);

        TxtLogin.setText(usuarioSelec.getLogin());
        TxtSenha.setText(usuarioSelec.getSenha());
        ComboboxCargo.setSelectedItem(usuarioSelec.getCargo());

    }//GEN-LAST:event_BtPesquisarActionPerformed

    private void configuraBotao(int opcao) {

        if (opcao == 1) {

            this.BtNovo.setVisible(false);
            this.BtEditar.setVisible(false);
            this.BtPesquisar.setVisible(false);
            this.Btgravar.setVisible(true);
            this.BtCancelar.setVisible(true);
            this.TxtSenha.setEnabled(true);
            this.TxtLogin.setEnabled(true);
            this.TxtConfirmaSenha.setEnabled(true);
            this.ComboboxCargo.setEnabled(true);
            BtExcluir.setVisible(false);

        } else {
            BtExcluir.setVisible(true);

            this.BtNovo.setVisible(true);
            this.BtEditar.setVisible(true);
            this.BtPesquisar.setVisible(true);
            this.Btgravar.setVisible(false);
            this.BtCancelar.setVisible(false);
            this.TxtSenha.setEnabled(false);
            this.TxtLogin.setEnabled(false);
            this.TxtConfirmaSenha.setEnabled(false);
            this.ComboboxCargo.setEnabled(false);
        }

    }

    public void iniciaSistema() {
 
        if (Files.exists(verificaSeExiste)) {

            try {
                /*
		    * Responsável por carregar o arquivo address.ser
		    * */
                FileInputStream fin = new FileInputStream(verificaSeExiste.toString());
                   
                /*
		    * Responsável por ler o objeto referente ao arquivo
		    * */
                ObjectInputStream ois = new ObjectInputStream(fin);

                /*
		    * Aqui a mágica é feita, onde os bytes presentes no arquivo address.ser
		    * são convertidos em uma instância de Address.
		    * */
                listaUsuarios = (ArrayList) ois.readObject();
                ois.close();

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    public boolean salvarUsuario() {
        try {


            /*
		 * A Classe FileOutputStream é responsável por criar
		 * o arquivo fisicamente no disco, assim poderemos realizar a 
		 * escrita neste. 
		 * */
            FileOutputStream fout = new FileOutputStream(verificaSeExiste.toString());

            /*
		 * A Classe ObjectOutputStream escreve os objetos no FileOutputStream
		 * */
            ObjectOutputStream object = new ObjectOutputStream(fout);

            /*
		 * Veja aqui a mágica ocorrendo: Estamos gravando um objeto 
		 * do tipo Address no arquivo address.ser. Atenção: O nosso 
		 * objeto Address que está sendo gravado, já é gravado de forma 
		 * serializada
		 * */
            object.writeObject(listaUsuarios);

            object.close();

            this.configuraBotao(2);

            return true;
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaUsuarios dialog = new TelaUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtCancelar;
    public javax.swing.JButton BtEditar;
    private javax.swing.JButton BtExcluir;
    public javax.swing.JButton BtNovo;
    public javax.swing.JButton BtPesquisar;
    public javax.swing.JButton Btgravar;
    public javax.swing.JComboBox<ClasseCadastro.Cargo> ComboboxCargo;
    private javax.swing.JLabel LabelCargo;
    private javax.swing.JLabel LabelConfirmaSenha;
    public javax.swing.JPasswordField TxtConfirmaSenha;
    public javax.swing.JTextField TxtLogin;
    public javax.swing.JPasswordField TxtSenha;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelSenha;
    // End of variables declaration//GEN-END:variables
}
