/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pesquisa;

import ClasseCadastro.Produto;
import Controller.controllerProduto;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jonathan - Vanila
 */
public class PesquisaProduto extends javax.swing.JDialog {

    controllerProduto controleProduto = new controllerProduto();
    DefaultTableModel modelo;
    private int codigoProduto;

    /**
     * Creates new form PesquisaProduto
     */
    public PesquisaProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        String[] colunas = new String[]{"Código", "Descrição", "Preço R$"};
        modelo = new DefaultTableModel(null, colunas);
        table.setModel(modelo);

        this.setProdutoSelecionado(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCodigo = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        labelPreco = new javax.swing.JLabel();
        txtpreco = new javax.swing.JTextField();
        labelDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btPesquisa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa Produto");

        labelCodigo.setText("Código:");

        labelPreco.setText("Preço: R$");

        labelDescricao.setText("Descrição:");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Preço R$"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        btPesquisa.setText("Pesquisar");
        btPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescricao)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelPreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtpreco))
                            .addComponent(labelDescricao))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btPesquisa)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigo)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPreco)
                    .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaActionPerformed
        this.modelo.getDataVector().removeAllElements();

        if (this.controleProduto.listaProdutoVazia()) {

            if (!(this.txtcodigo.getText().isEmpty())) {
                if (this.controleProduto.verificaProduto(Integer.parseInt(this.txtcodigo.getText()))) {
                    Produto produto;
                    produto = this.controleProduto.pesquisarProduto(Integer.parseInt(this.txtcodigo.getText()));

                    if (!(produto.getDescricao().isEmpty())) {
                        modelo.addRow(new Object[]{produto.getCodigo(), produto.getDescricao(), produto.getValor()});
                    }
                }
            } else {

                List<Produto> lista = this.controleProduto.listatodosProdutos();

                if (this.txtpreco.getText().isEmpty() && !this.txtDescricao.getText().isEmpty()) {
                    for (int i = 0; i < lista.size(); i++) {

                        if (lista.get(i).getDescricao().equalsIgnoreCase(this.txtDescricao.getText())) {
                            modelo.addRow(new Object[]{lista.get(i).getCodigo(), lista.get(i).getDescricao(), lista.get(i).getValor()});
                        }
                    }
                } else if (!this.txtpreco.getText().isEmpty() && this.txtDescricao.getText().isEmpty()) {
                    for (int i = 0; i < lista.size(); i++) {

                        if (lista.get(i).getValor() == Float.parseFloat(this.txtpreco.getText())) {
                            modelo.addRow(new Object[]{lista.get(i).getCodigo(), lista.get(i).getDescricao(), lista.get(i).getValor()});
                        }
                    }
                } else if (!this.txtpreco.getText().isEmpty() && !this.txtDescricao.getText().isEmpty()) {

                    for (int i = 0; i < lista.size(); i++) {

                        if (lista.get(i).getValor() == Float.parseFloat(this.txtpreco.getText()) && lista.get(i).getDescricao().equalsIgnoreCase(this.txtDescricao.getText())) {
                            modelo.addRow(new Object[]{lista.get(i).getCodigo(), lista.get(i).getDescricao(), lista.get(i).getValor()});
                        }
                    }

                } else {
                    for (int i = 0; i < lista.size(); i++) {
                        modelo.addRow(new Object[]{lista.get(i).getCodigo(), lista.get(i).getDescricao(), lista.get(i).getValor()});
                    }
                }
            }
        }
    }//GEN-LAST:event_btPesquisaActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        if (evt.getClickCount() == 1) {

            int selecionado = table.getSelectedRow();

            if (selecionado != -1) {
                this.setProdutoSelecionado((int) table.getValueAt(selecionado, 0));
                this.dispose();

            }
        }
    }//GEN-LAST:event_tableMouseClicked

    public int getProdutoSelecionado() {
        return codigoProduto;
    }

    private void setProdutoSelecionado(int codigo) {
        this.codigoProduto = codigo;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PesquisaProduto dialog = new PesquisaProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtpreco;
    // End of variables declaration//GEN-END:variables
}
