/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhoprogramacao2;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author junio_000
 */
public class TelaPagamento extends javax.swing.JDialog {
    private final double totalPagar;
    private boolean finalizou = false;

    /**
     * Creates new form TelaPagamento
     */
    public TelaPagamento(java.awt.Frame parent, double totalPagar) {
        super(parent, true);
        initComponents();
        this.totalPagar = totalPagar;
        this.tfTotalPagar.setText(String.valueOf(this.totalPagar));
        this.atualizaValorCampos();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTotalPagar = new javax.swing.JLabel();
        tfTotalPagar = new javax.swing.JTextField();
        lbFaltaPagar = new javax.swing.JLabel();
        tfFaltaPagar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfTroco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btFinalizar = new javax.swing.JButton();
        NumberFormatter nf = new NumberFormatter(DecimalFormat.getCurrencyInstance());
        nf.setAllowsInvalid(false);
        nf.setValueClass(Double.class);
        tfPago = new javax.swing.JFormattedTextField(nf);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbTotalPagar.setText("Total à pagar: ");

        tfTotalPagar.setEditable(false);
        tfTotalPagar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotalPagar.setText("0.0");

        lbFaltaPagar.setText("Falta:");

        tfFaltaPagar.setEditable(false);
        tfFaltaPagar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfFaltaPagar.setText("0.0");
        tfFaltaPagar.setToolTipText("");

        jLabel1.setText("Pago:");

        tfTroco.setEditable(false);
        tfTroco.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTroco.setText("0.0");

        jLabel2.setText("Troco: ");

        btFinalizar.setText("Finalizar");
        btFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalizarActionPerformed(evt);
            }
        });

        tfPago.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfPago.setText("0.0");
        tfPago.setValue(new Double(0.0));
        tfPago.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tfPagoPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btFinalizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(lbFaltaPagar)
                            .addComponent(lbTotalPagar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTotalPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(tfFaltaPagar)
                            .addComponent(tfTroco)
                            .addComponent(tfPago))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotalPagar)
                    .addComponent(tfTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFaltaPagar)
                    .addComponent(tfFaltaPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFinalizar)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPagoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tfPagoPropertyChange
        atualizaValorCampos();
    }//GEN-LAST:event_tfPagoPropertyChange

    private void btFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalizarActionPerformed
        if ((double) this.tfPago.getValue() < this.totalPagar) {
            JOptionPane.showMessageDialog(this, "O valor pago é menor que o total a pagar!");
            tfTotalPagar.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Mesa fechada com sucesso!");
            this.finalizou = true;
            this.dispose();
        }
    }//GEN-LAST:event_btFinalizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbFaltaPagar;
    private javax.swing.JLabel lbTotalPagar;
    private javax.swing.JTextField tfFaltaPagar;
    private javax.swing.JFormattedTextField tfPago;
    private javax.swing.JTextField tfTotalPagar;
    private javax.swing.JTextField tfTroco;
    // End of variables declaration//GEN-END:variables

    private void atualizaValorCampos() {
        double valorPago = (double) (this.tfPago.getValue());
        if (valorPago > this.totalPagar) {
            this.tfTroco.setText(String.valueOf(valorPago - this.totalPagar));
            this.tfFaltaPagar.setText("0.0");
        } else {
            this.tfFaltaPagar.setText(String.valueOf(this.totalPagar - valorPago));
            this.tfTroco.setText("0.0");
        }
        
    }
    
    public boolean success() {
        return finalizou;
    }
}
