/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhoProgramacao2.apresentacao;

import trabalhoProgramacao2.controle.Cargo;
import trabalhoProgramacao2.controle.Usuario;
import trabalhoProgramacao2.modelo.ControllerUsuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Vanila
 */
public class TelaUsuarios extends javax.swing.JDialog {

    trabalhoProgramacao2.modelo.ControllerUsuario controleUsario = new ControllerUsuario();

    /**
     * Creates new form TelaUsuarios
     */
    public TelaUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controleUsario.carregaListaUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboboxCargo = new javax.swing.JComboBox<>(trabalhoProgramacao2.controle.Cargo.values());
        labelCargo = new javax.swing.JLabel();
        btEditar = new javax.swing.JButton();
        labelLogin = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();
        txtLogin = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        btExcluir = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        btNovo = new javax.swing.JButton();
        txtConfirmaSenha = new javax.swing.JPasswordField();
        labelConfirmaSenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuário");

        comboboxCargo.setEditable(true);
        comboboxCargo.setEnabled(false);

        labelCargo.setText("Cargo:");

        btEditar.setText("Editar");
        btEditar.setAlignmentY(0.0F);
        btEditar.setEnabled(false);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        labelLogin.setText("Login:");

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        txtLogin.setEnabled(false);

        labelSenha.setText("Senha:");

        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        txtSenha.setEnabled(false);

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        txtConfirmaSenha.setEnabled(false);

        labelConfirmaSenha.setText("Confirme a senha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboboxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSenha)
                            .addComponent(labelConfirmaSenha)
                            .addComponent(labelCargo)
                            .addComponent(labelLogin))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtLogin, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSenha)
                            .addComponent(txtConfirmaSenha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(btEditar)
                                .addGap(1, 1, 1)
                                .addComponent(btPesquisar)))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelConfirmaSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(labelCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btPesquisar)
                    .addComponent(btExcluir)
                    .addComponent(btNovo)
                    .addComponent(btEditar))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        this.configuraBotao(1);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        this.configuraBotao(1);
        this.btEditar.setEnabled(false);
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        controleUsario.removeUsuario(this.txtLogin.getText());
        this.configuraBotao(2);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        Pesquisa pesquisar = new Pesquisa(null, true);

        pesquisar.setLocationRelativeTo(null);
        pesquisar.setModal(true);
        pesquisar.setVisible(true);

        if (!(pesquisar.getNomeSelecionado().isEmpty())) {
            Usuario usuarioSelecionado = controleUsario.pesquisarUsuario(pesquisar.getNomeSelecionado());

            txtLogin.setText(usuarioSelecionado.getLogin());
            txtSenha.setText(usuarioSelecionado.getSenha());
            comboboxCargo.setSelectedItem(usuarioSelecionado.getCargo());

            this.btEditar.setEnabled(true);
            this.btExcluir.setEnabled(true);
        }

    }//GEN-LAST:event_btPesquisarActionPerformed

    private void BtgravarActionPerformed(java.awt.event.ActionEvent evt) {

        if (this.txtSenha.getText().equals(this.txtConfirmaSenha.getText())) {

            if (this.txtLogin.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Por favor para prosegui insira um login válido");

            } else if (this.txtSenha.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Por favor para prosegui insira uma senha válida");

            } else {
                controleUsario.gravarUsuario(this.txtLogin.getText(), this.txtSenha.getText(), (Cargo) comboboxCargo.getSelectedItem());
                this.configuraBotao(2);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Senhas diferentes por favor verifique!.");
        }

    }

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar?", "Atenção", JOptionPane.YES_NO_OPTION) == 0) {
            txtLogin.setText(null);
            txtSenha.setText(null);
            txtConfirmaSenha.setText(null);
            configuraBotao(2);
        }
    }

    private void configuraBotao(int opcao) {

        if (opcao == 1) {

            this.btPesquisar.setEnabled(false);
            this.txtSenha.setEnabled(true);
            this.txtLogin.setEnabled(true);
            this.txtConfirmaSenha.setEnabled(true);
            this.comboboxCargo.setEnabled(true);
            this.btExcluir.setEnabled(true);

            this.btNovo.removeActionListener(this.btNovo.getActionListeners()[0]);
            this.btNovo.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    BtgravarActionPerformed(e);
                }
            });
            this.btNovo.setText("Gravar");

            this.btExcluir.removeActionListener(this.btExcluir.getActionListeners()[0]);
            this.btExcluir.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    BtCancelarActionPerformed(e);
                }
            });

            this.btExcluir.setText("Cancelar");

        } else {

            this.btPesquisar.setEnabled(true);
            this.txtSenha.setEnabled(false);
            this.txtLogin.setEnabled(false);
            this.txtConfirmaSenha.setEnabled(false);
            this.comboboxCargo.setEnabled(false);
            this.btEditar.setEnabled(false);
            this.txtLogin.setText(null);
            this.txtSenha.setText(null);
            this.btExcluir.setEnabled(false);
            this.txtConfirmaSenha.setText(null);

            this.btNovo.removeActionListener(this.btNovo.getActionListeners()[0]);
            this.btNovo.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    btNovoActionPerformed(e);
                }
            });
            this.btNovo.setText("Novo");

            this.btExcluir.removeActionListener(this.btExcluir.getActionListeners()[0]);
            this.btExcluir.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    btExcluirActionPerformed(e);
                }
            });
            this.btExcluir.setText("Excluir");

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaUsuarios dialog = new TelaUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    public javax.swing.JButton btNovo;
    public javax.swing.JButton btPesquisar;
    public javax.swing.JComboBox<trabalhoProgramacao2.controle.Cargo> comboboxCargo;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelConfirmaSenha;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelSenha;
    public javax.swing.JPasswordField txtConfirmaSenha;
    public javax.swing.JTextField txtLogin;
    public javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
